# Generated by Django 5.1.2 on 2024-11-02 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_emailanalysis_recipient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailanalysis',
            name='recipient',
        ),
    ]
